import { NextResponse } from 'next/server'
import { auth } from '@/auth'
import { prisma } from '@/lib/prisma'

export const dynamic = 'force-dynamic'

// Escape a single value for SQL INSERT
function sqlVal(v: unknown): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'boolean') return v ? '1' : '0'
  if (typeof v === 'number') return String(v)
  if (v instanceof Date) return `'${v.toISOString().replace('T', ' ').slice(0, 19)}'`
  if (typeof v === 'object') {
    // JSON columns
    return `'${JSON.stringify(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  }
  // String — escape backslashes then single quotes
  return `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function insertStatements(table: string, rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return `-- ${table}: no data\n`
  const cols = Object.keys(rows[0]).map((c) => `\`${c}\``).join(', ')
  const lines = rows.map(
    (row) => `INSERT INTO \`${table}\` (${cols}) VALUES (${Object.values(row).map(sqlVal).join(', ')});`
  )
  return lines.join('\n') + '\n'
}

export async function GET() {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  if (session.user.role !== 'SUPER_ADMIN') return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  // Fetch all tables in parallel — passwordHash excluded from users
  const [
    users,
    assessments,
    categories,
    indicators,
    rubrics,
    rubricItems,
    versions,
    indicatorChanges,
    userStatuses,
    selfAssessments,
    validations,
    backups,
    draftBackups,
    auditLogs,
  ] = await Promise.all([
    prisma.user.findMany({
      select: {
        id: true, name: true, email: true, role: true,
        kabupatenName: true, kecamatanName: true,
        kabupatenId: true, kecamatanId: true,
        isActive: true, createdAt: true, updatedAt: true,
      },
      orderBy: { id: 'asc' },
    }),
    prisma.assessment.findMany({ orderBy: { id: 'asc' } }),
    prisma.assessmentCategory.findMany({ orderBy: { id: 'asc' } }),
    prisma.assessmentIndicator.findMany({ orderBy: { id: 'asc' } }),
    prisma.assessmentRubric.findMany({ orderBy: { id: 'asc' } }),
    prisma.rubricItem.findMany({ orderBy: { id: 'asc' } }),
    prisma.assessmentVersion.findMany({ orderBy: { id: 'asc' } }),
    prisma.indicatorChange.findMany({ orderBy: { id: 'asc' } }),
    prisma.userAssessmentStatus.findMany({ orderBy: { id: 'asc' } }),
    prisma.selfAssessment.findMany({ orderBy: { id: 'asc' } }),
    prisma.assessmentValidation.findMany({ orderBy: { id: 'asc' } }),
    prisma.assessmentBackup.findMany({ orderBy: { id: 'asc' } }),
    prisma.assessmentDraftBackup.findMany({ orderBy: { createdAt: 'asc' } }),
    prisma.auditLog.findMany({ orderBy: { id: 'asc' } }),
  ])

  const stamp = new Date().toISOString().replace('T', '_').slice(0, 16).replace(':', '-')

  const sections: string[] = [
    `-- Klas Berdaya — Full Database Backup`,
    `-- Generated: ${new Date().toISOString()}`,
    `-- Generated by: ${session.user.name} (${session.user.email})`,
    `-- NOTE: passwordHash excluded from users table`,
    ``,
    `SET FOREIGN_KEY_CHECKS=0;`,
    ``,
    `-- users`,
    insertStatements('users', users as Record<string, unknown>[]),
    `-- assessments`,
    insertStatements('assessments', assessments as Record<string, unknown>[]),
    `-- assessment_categories`,
    insertStatements('assessment_categories', categories as Record<string, unknown>[]),
    `-- assessment_indicators`,
    insertStatements('assessment_indicators', indicators as Record<string, unknown>[]),
    `-- assessment_rubrics`,
    insertStatements('assessment_rubrics', rubrics as Record<string, unknown>[]),
    `-- rubric_items`,
    insertStatements('rubric_items', rubricItems as Record<string, unknown>[]),
    `-- assessment_versions`,
    insertStatements('assessment_versions', versions as Record<string, unknown>[]),
    `-- indicator_changes`,
    insertStatements('indicator_changes', indicatorChanges as Record<string, unknown>[]),
    `-- user_assessment_status`,
    insertStatements('user_assessment_status', userStatuses as Record<string, unknown>[]),
    `-- self_assessments`,
    insertStatements('self_assessments', selfAssessments as Record<string, unknown>[]),
    `-- assessment_validations`,
    insertStatements('assessment_validations', validations as Record<string, unknown>[]),
    `-- assessment_backups`,
    insertStatements('assessment_backups', backups as Record<string, unknown>[]),
    `-- assessment_draft_backups`,
    insertStatements('assessment_draft_backups', draftBackups as Record<string, unknown>[]),
    `-- audit_logs`,
    insertStatements('audit_logs', auditLogs as Record<string, unknown>[]),
    ``,
    `SET FOREIGN_KEY_CHECKS=1;`,
  ]

  const sql = sections.join('\n')

  return new NextResponse(sql, {
    headers: {
      'Content-Type': 'application/sql',
      'Content-Disposition': `attachment; filename="backup-${stamp}.sql"`,
      'Cache-Control': 'no-store',
    },
  })
}
